// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoqwfFGRSVo2wsgVSvDX8g6_OsflJvQK8',
    appId: '1:234230569304:web:2918f57fa2bb27c040ad2d',
    messagingSenderId: '234230569304',
    projectId: 'kudirat-notes-app',
    authDomain: 'kudirat-notes-app.firebaseapp.com',
    storageBucket: 'kudirat-notes-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxNDoXlA9SbwRB5nwsD-B4uuFu4qcUvAY',
    appId: '1:234230569304:android:9cdcbdf361be722840ad2d',
    messagingSenderId: '234230569304',
    projectId: 'kudirat-notes-app',
    storageBucket: 'kudirat-notes-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlUjlq6ZqYCsBHqcYdfTeszTdUkVMvtj4',
    appId: '1:234230569304:ios:b30b8ec0e23f787240ad2d',
    messagingSenderId: '234230569304',
    projectId: 'kudirat-notes-app',
    storageBucket: 'kudirat-notes-app.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );
}
